name: NPM Publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm run install:lib
          npm run build:lib

      - name: setup-node@v2
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish lib to NPM
        run: npm publish lib/ --access public
        continue-on-error: true
